# Generated by Codex on 2026-05-01
from django.db import migrations


def create_roles(apps, schema_editor):
    group_model = apps.get_model('auth', 'Group')
    for role_name in ['kasir', 'pembelian', 'admin_toko']:
        group_model.objects.get_or_create(name=role_name)


def remove_roles(apps, schema_editor):
    group_model = apps.get_model('auth', 'Group')
    group_model.objects.filter(name__in=['kasir', 'pembelian', 'admin_toko']).delete()


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.RunPython(create_roles, remove_roles),
    ]
