# Generated by Django 6.0.4 on 2026-09-23 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_add_member_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('access_pos', 'Akses Kasir POS'), ('void_sale', 'Batalkan / Void Transaksi POS'), ('reprint_receipt', 'Cetak Ulang Struk Kasir'), ('view_sales_reports', 'Akses Laporan Penjualan & Laba Rugi'), ('view_inventory', 'Lihat Master Produk & Stok'), ('manage_products', 'Kelola Master Produk & Harga Tier'), ('manage_purchases', 'Kelola Kulakan / Pembelian'), ('perform_stock_opname', 'Melakukan Stock Opname'), ('perform_daily_closing', 'Melakukan Tutup Harian'), ('reopen_daily_closing', 'Buka Kembali Tutup Harian'), ('view_members', 'Lihat Data Anggota & Kartu'), ('manage_members', 'Kelola Master Anggota & Kartu'), ('validate_topup', 'Validasi / Approve Topup Saldo'), ('withdraw_deposit', 'Tarik Saldo Deposit Anggota'), ('reverse_transactions', 'Reversal Topup / Tarik Deposit'), ('manage_staff', 'Kelola Akun & Penugasan Role Staff'), ('manage_role_permissions', 'Atur Matriks Izin Role')],
                'managed': False,
                'default_permissions': (),
            },
        ),
    ]
