# Generated by Django 6.0.4 on 2026-09-25 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_setup_default_role_permissions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appaccess',
            options={'default_permissions': (), 'managed': False, 'permissions': [('access_pos', 'Akses Kasir POS'), ('void_sale', 'Batalkan / Void Transaksi POS'), ('reprint_receipt', 'Cetak Ulang Struk Kasir'), ('view_sales_reports', 'Akses Laporan Penjualan & Laba Rugi'), ('view_inventory', 'Lihat Master Produk & Stok'), ('manage_products', 'Kelola Master Produk & Harga Tier'), ('manage_purchases', 'Kelola Kulakan / Pembelian'), ('manage_consignments', 'Kelola Barang Titipan / Konsinyasi'), ('perform_stock_opname', 'Melakukan Stock Opname'), ('perform_daily_closing', 'Melakukan Tutup Harian'), ('reopen_daily_closing', 'Buka Kembali Tutup Harian'), ('view_members', 'Lihat Data Anggota & Kartu'), ('manage_members', 'Kelola Master Anggota & Kartu'), ('validate_topup', 'Validasi / Approve Topup Saldo'), ('withdraw_deposit', 'Tarik Saldo Deposit Anggota'), ('reverse_transactions', 'Reversal Topup / Tarik Deposit'), ('manage_staff', 'Kelola Akun & Penugasan Role Staff'), ('manage_role_permissions', 'Atur Matriks Izin Role')]},
        ),
    ]
