# Generated by Django 6.0.4 on 2026-09-27 13:55

import uuid
from django.db import migrations, models


def grant_manage_settings(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')
    ContentType = apps.get_model('contenttypes', 'ContentType')

    ct, _ = ContentType.objects.get_or_create(app_label='core', model='appaccess')
    perm, _ = Permission.objects.get_or_create(
        codename='manage_settings',
        content_type=ct,
        defaults={'name': 'Kelola Pengaturan Toko & POS'}
    )

    admin_group = Group.objects.filter(name='admin_toko').first()
    if admin_group:
        admin_group.permissions.add(perm)


def revert_grant(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_grant_manage_consignments'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store_name', models.CharField(default='Koperasi', max_length=150, verbose_name='Nama Toko / Koperasi')),
                ('store_address', models.CharField(blank=True, default='', max_length=255, verbose_name='Alamat Toko')),
                ('store_phone', models.CharField(blank=True, default='', max_length=50, verbose_name='No. Telepon / WhatsApp')),
                ('receipt_footer', models.CharField(blank=True, default='Terima Kasih Atas Kunjungan Anda', max_length=255, verbose_name='Catatan Footer Struk (Catatan Kaki)')),
                ('pos_allow_negative_stock', models.BooleanField(default=False, help_text='Jika aktif, kasir dapat menyelesaikan penjualan saat stok sistem 0 atau kurang (stok tercatat minus hingga barang masuk diinput gudang).', verbose_name='Izinkan Transaksi POS Saat Stok Habis / Minus')),
            ],
            options={
                'verbose_name': 'Pengaturan Toko & POS',
                'verbose_name_plural': 'Pengaturan Toko & POS',
            },
        ),
        migrations.AlterModelOptions(
            name='appaccess',
            options={'default_permissions': (), 'managed': False, 'permissions': [('access_pos', 'Akses Kasir POS'), ('void_sale', 'Batalkan / Void Transaksi POS'), ('reprint_receipt', 'Cetak Ulang Struk Kasir'), ('view_sales_reports', 'Akses Laporan Penjualan & Laba Rugi'), ('view_inventory', 'Lihat Master Produk & Stok'), ('manage_products', 'Kelola Master Produk & Harga Tier'), ('manage_purchases', 'Kelola Kulakan / Pembelian'), ('manage_consignments', 'Kelola Barang Titipan / Konsinyasi'), ('perform_stock_opname', 'Melakukan Stock Opname'), ('perform_daily_closing', 'Melakukan Tutup Harian'), ('reopen_daily_closing', 'Buka Kembali Tutup Harian'), ('view_members', 'Lihat Data Anggota & Kartu'), ('manage_members', 'Kelola Master Anggota & Kartu'), ('validate_topup', 'Validasi / Approve Topup Saldo'), ('withdraw_deposit', 'Tarik Saldo Deposit Anggota'), ('reverse_transactions', 'Reversal Topup / Tarik Deposit'), ('manage_staff', 'Kelola Akun & Penugasan Role Staff'), ('manage_role_permissions', 'Atur Matriks Izin Role'), ('manage_settings', 'Kelola Pengaturan Toko & POS')]},
        ),
        migrations.RunPython(grant_manage_settings, revert_grant),
    ]
