# Generated by Django 6.0.4 on 2026-10-01 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_storesetting_alter_appaccess_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginSecurityRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(db_index=True, max_length=150, unique=True)),
                ('failed_count', models.PositiveIntegerField(default=0)),
                ('last_attempt_at', models.DateTimeField(auto_now=True)),
                ('locked_until', models.DateTimeField(blank=True, db_index=True, null=True)),
            ],
            options={
                'verbose_name': 'Audit Percobaan Login',
                'verbose_name_plural': 'Audit Percobaan Login',
                'ordering': ['-last_attempt_at'],
            },
        ),
    ]
