from django.urls import path

from . import views
from . import views_consignment

urlpatterns = [
    path('products/', views.product_list, name='product_list'),
    path('products/create/', views.product_create, name='product_create'),
    path('products/import/', views.product_import_excel, name='product_import_excel'),
    path('products/import/template/', views.product_import_template_excel, name='product_import_template_excel'),
    path('products/<uuid:uuid>/', views.product_detail, name='product_detail'),
    path('products/<uuid:uuid>/edit/', views.product_edit, name='product_edit'),
    path('products/<uuid:uuid>/delete/', views.product_delete, name='product_delete'),
    path('units/', views.unit_list, name='unit_list'),
    path('units/create/', views.unit_create, name='unit_create'),
    path('units/<uuid:uuid>/', views.unit_detail, name='unit_detail'),
    path('units/<uuid:uuid>/edit/', views.unit_edit, name='unit_edit'),
    path('units/<uuid:uuid>/delete/', views.unit_delete, name='unit_delete'),
    path('suppliers/', views.supplier_list, name='supplier_list'),
    path('suppliers/create/', views.supplier_create, name='supplier_create'),
    path('suppliers/<uuid:uuid>/', views.supplier_detail, name='supplier_detail'),
    path('suppliers/<uuid:uuid>/edit/', views.supplier_edit, name='supplier_edit'),
    path('suppliers/<uuid:uuid>/delete/', views.supplier_delete, name='supplier_delete'),
    path('purchases/', views.purchase_page, name='purchase_page'),
    path('purchases/create/', views.purchase_create, name='purchase_create'),
    path('purchases/<uuid:uuid>/', views.purchase_detail, name='purchase_detail'),
    path('purchases/<uuid:uuid>/edit/', views.purchase_edit, name='purchase_edit'),
    path('purchases/<uuid:uuid>/delete/', views.purchase_delete, name='purchase_delete'),
    path('internal-used/', views.internal_used_page, name='internal_used_page'),
    path('stock-opname/', views.stock_opname_page, name='stock_opname_page'),
    path('daily-closing/', views.daily_closing_page, name='daily_closing_page'),
    path('daily-closing/report/', views.daily_closing_report, name='daily_closing_report'),
    path('reports/stock-card/', views.stock_card_report, name='stock_card_report'),
    path('reorder-alert/', views.reorder_alert_page, name='reorder_alert_page'),
    path('categories/', views.category_list, name='category_list'),
    path('categories/create/', views.category_create, name='category_create'),
    path('categories/<uuid:uuid>/', views.category_detail, name='category_detail'),
    path('categories/<uuid:uuid>/edit/', views.category_edit, name='category_edit'),
    path('categories/<uuid:uuid>/delete/', views.category_delete, name='category_delete'),

    # Barang Titipan (Konsinyasi)
    path('consignors/', views_consignment.consignor_list, name='consignor_list'),
    path('consignors/create/', views_consignment.consignor_create, name='consignor_create'),
    path('consignors/<uuid:uuid>/', views_consignment.consignor_detail, name='consignor_detail'),
    path('consignors/<uuid:uuid>/edit/', views_consignment.consignor_edit, name='consignor_edit'),
    path('consignors/<uuid:uuid>/products/create/', views_consignment.consignor_product_create, name='consignor_product_create'),
    path('consignors/<int:consignor_id>/products/create-api/', views_consignment.consignor_product_create_api, name='consignor_product_create_api'),
    path('consignors/<int:consignor_id>/products/json/', views_consignment.consignor_products_json, name='consignor_products_json'),
    path('consignments/inflow/', views_consignment.consignment_inflow, name='consignment_inflow'),
    path('consignments/batches/<uuid:uuid>/receipt/', views_consignment.consignment_batch_receipt, name='consignment_batch_receipt'),
    path('consignments/settlement/', views_consignment.consignment_settlement_list, name='consignment_settlement_list'),
    path('consignments/batches/<uuid:uuid>/settle/', views_consignment.consignment_settle_detail, name='consignment_settle_detail'),
    path('consignments/batches/<uuid:uuid>/settle-receipt/', views_consignment.consignment_settle_receipt, name='consignment_settle_receipt'),
    path('consignments/batches/<uuid:uuid>/cancel/', views_consignment.consignment_batch_cancel, name='consignment_batch_cancel'),
    path('consignments/reports/', views_consignment.consignment_report, name='consignment_report'),
]
