from django.urls import path

from . import views

urlpatterns = [
    path('products/', views.product_list, name='product_list'),
    path('products/create/', views.product_create, name='product_create'),
    path('products/<uuid:uuid>/', views.product_detail, name='product_detail'),
    path('products/<uuid:uuid>/edit/', views.product_edit, name='product_edit'),
    path('products/<uuid:uuid>/delete/', views.product_delete, name='product_delete'),
    path('units/', views.unit_list, name='unit_list'),
    path('units/create/', views.unit_create, name='unit_create'),
    path('units/<uuid:uuid>/', views.unit_detail, name='unit_detail'),
    path('units/<uuid:uuid>/edit/', views.unit_edit, name='unit_edit'),
    path('units/<uuid:uuid>/delete/', views.unit_delete, name='unit_delete'),
    path('suppliers/', views.supplier_list, name='supplier_list'),
    path('suppliers/create/', views.supplier_create, name='supplier_create'),
    path('suppliers/<uuid:uuid>/', views.supplier_detail, name='supplier_detail'),
    path('suppliers/<uuid:uuid>/edit/', views.supplier_edit, name='supplier_edit'),
    path('suppliers/<uuid:uuid>/delete/', views.supplier_delete, name='supplier_delete'),
    path('purchases/', views.purchase_page, name='purchase_page'),
    path('purchases/create/', views.purchase_create, name='purchase_create'),
    path('purchases/<uuid:uuid>/', views.purchase_detail, name='purchase_detail'),
    path('purchases/<uuid:uuid>/edit/', views.purchase_edit, name='purchase_edit'),
    path('purchases/<uuid:uuid>/delete/', views.purchase_delete, name='purchase_delete'),
    path('internal-used/', views.internal_used_page, name='internal_used_page'),
    path('stock-opname/', views.stock_opname_page, name='stock_opname_page'),
    path('daily-closing/', views.daily_closing_page, name='daily_closing_page'),
    path('reports/stock-card/', views.stock_card_report, name='stock_card_report'),
    path('reorder-alert/', views.reorder_alert_page, name='reorder_alert_page'),
    path('categories/', views.category_list, name='category_list'),
    path('categories/create/', views.category_create, name='category_create'),
    path('categories/<uuid:uuid>/', views.category_detail, name='category_detail'),
    path('categories/<uuid:uuid>/edit/', views.category_edit, name='category_edit'),
    path('categories/<uuid:uuid>/delete/', views.category_delete, name='category_delete'),
]
