# Generated by Django 6.0.4 on 2026-05-02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productpricetier',
            name='discount_type',
            field=models.CharField(blank=True, choices=[('percent', 'Persen'), ('nominal', 'Nominal')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='productpricetier',
            name='discount_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='productpricetier',
            name='source_mode',
            field=models.CharField(choices=[('final', 'Harga Jadi'), ('discount', 'Diskon')], default='final', max_length=10),
        ),
    ]
