# Generated by Django 6.0.4 on 2026-05-06 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_supplier_city_supplier_code_supplier_contact_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='barcode',
            field=models.CharField(blank=True, max_length=80, null=True, unique=True),
        ),
    ]
