# Generated by Django 6.0.4 on 2026-05-06 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_product_barcode'),
        ('members', '0005_alter_memberledger_member_alter_membertopup_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorytransaction',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_transactions', to='members.member'),
        ),
    ]
