# Generated by Django 6.0.4 on 2026-05-10 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_alter_inventorytransaction_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cost_of_goods_sold',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
    ]
