# Generated by Django 6.0.4 on 2026-09-24 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_product_cost_of_goods_sold'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='allow_decimal_qty',
            field=models.BooleanField(default=False, verbose_name='Bisa Dijual Pecahan / Curah'),
        ),
        migrations.AlterField(
            model_name='inventorytransactionitem',
            name='qty',
            field=models.DecimalField(decimal_places=3, max_digits=12),
        ),
        migrations.AlterField(
            model_name='product',
            name='reorder_point',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='productpricetier',
            name='max_qty',
            field=models.DecimalField(decimal_places=3, default=999999, max_digits=12),
        ),
        migrations.AlterField(
            model_name='productpricetier',
            name='min_qty',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=12),
        ),
        migrations.AlterField(
            model_name='stockledger',
            name='balance_after',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='stockledger',
            name='balance_before',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='stockledger',
            name='qty_in',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='stockledger',
            name='qty_out',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12),
        ),
    ]
