# Generated by Django 6.0.4 on 2026-09-25 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_product_allow_decimal_qty_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdailysnapshot',
            name='closing_stock',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='productdailysnapshot',
            name='mutation_in',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='productdailysnapshot',
            name='mutation_out',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='productdailysnapshot',
            name='opening_stock',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12),
        ),
    ]
