# Generated by Django 6.0.4 on 2026-09-25 04:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_alter_productdailysnapshot_closing_stock_and_more'),
        ('members', '0009_memberdepositauditlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_consignment',
            field=models.BooleanField(default=False, verbose_name='Barang Titipan / Konsinyasi'),
        ),
        migrations.AlterField(
            model_name='inventorytransaction',
            name='tx_type',
            field=models.CharField(choices=[('purchase', 'Purchase'), ('internal_used', 'Internal Used'), ('pos_sale', 'POS Sale'), ('stock_opname', 'Stock Opname'), ('daily_closing', 'Daily Closing'), ('consignment_in', 'Consignment Inflow (Titipan Pagi)'), ('consignment_return', 'Consignment Return (Retur Sore)')], max_length=20),
        ),
        migrations.CreateModel(
            name='ConsignmentBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch_number', models.CharField(db_index=True, max_length=40, unique=True)),
                ('batch_date', models.DateField(db_index=True)),
                ('status', models.CharField(choices=[('open', 'Aktif (Sedang Berjalan)'), ('settled', 'Selesai (Sudah Rekap & Bayar)'), ('cancelled', 'Dibatalkan')], db_index=True, default='open', max_length=20)),
                ('total_received_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_sold_cost', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_sold_retail', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_coop_margin', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('payout_method', models.CharField(blank=True, choices=[('cash', 'Tunai (Kas Toko)'), ('member_deposit', 'Deposit Dompet Anggota'), ('transfer', 'Transfer Bank')], default='', max_length=20)),
                ('payout_reference', models.CharField(blank=True, default='', max_length=100)),
                ('settled_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_consignments', to=settings.AUTH_USER_MODEL)),
                ('inflow_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consignment_inflows', to='inventory.inventorytransaction')),
                ('return_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consignment_returns', to='inventory.inventorytransaction')),
                ('settled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settled_consignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-batch_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConsignmentBatchItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cost_price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('qty_received', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('qty_sold', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('qty_returned', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('qty_loss', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('payable_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('coop_margin', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.consignmentbatch')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consignment_batch_items', to='inventory.product')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Consignor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(db_index=True, help_text='Kode unik penitip, misal: P01, IBU-SITI', max_length=30, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('phone', models.CharField(blank=True, default='', max_length=30)),
                ('address', models.CharField(blank=True, default='', max_length=255)),
                ('bank_name', models.CharField(blank=True, default='', max_length=50)),
                ('bank_account', models.CharField(blank=True, default='', max_length=50)),
                ('bank_account_holder', models.CharField(blank=True, default='', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consignors_created', to=settings.AUTH_USER_MODEL)),
                ('member', models.ForeignKey(blank=True, help_text='Tautkan jika penitip adalah anggota koperasi', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consignors', to='members.member')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consignors_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='consignmentbatch',
            name='consignor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batches', to='inventory.consignor'),
        ),
        migrations.AddField(
            model_name='inventorytransaction',
            name='consignor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_transactions', to='inventory.consignor'),
        ),
        migrations.AddField(
            model_name='product',
            name='consignor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='inventory.consignor'),
        ),
    ]
