# Generated by Django 6.0.4 on 2026-05-02 07:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='member_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='membertopup',
            name='effective_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='membertopup',
            name='kind',
            field=models.CharField(choices=[('member_request', 'Member Request'), ('admin_direct', 'Admin Direct'), ('admin_bulk', 'Admin Bulk'), ('reversal', 'Reversal')], default='member_request', max_length=20),
        ),
        migrations.AddField(
            model_name='membertopup',
            name='proof_file',
            field=models.FileField(blank=True, null=True, upload_to='topup_proofs/'),
        ),
        migrations.AddField(
            model_name='membertopup',
            name='requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='member_topup_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='membertopup',
            name='reversal_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reversal_entries', to='members.membertopup'),
        ),
        migrations.AddField(
            model_name='membertopup',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('reversed', 'Reversed')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='membertopup',
            name='validated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='membertopup',
            name='validated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='member_topup_validations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='membertopup',
            name='validation_note',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='memberledger',
            name='txn_type',
            field=models.CharField(choices=[('topup', 'Topup'), ('purchase', 'Purchase'), ('adjustment', 'Adjustment'), ('refund', 'Refund'), ('reversal_topup', 'Reversal Topup')], max_length=20),
        ),
    ]
