# Generated by Django 6.0.4 on 2026-05-02 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_member_user_membertopup_effective_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='membertopup',
            name='topup_number',
            field=models.CharField(blank=True, db_index=True, default='', max_length=40, unique=True),
        ),
        migrations.AddField(
            model_name='membertopup',
            name='topup_type',
            field=models.CharField(choices=[('member', 'Member'), ('admin', 'Admin'), ('system', 'System')], default='member', max_length=20),
        ),
    ]
