# Generated by Django 6.0.4 on 2026-05-04 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_membertopup_topup_number_membertopup_topup_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='code',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
    ]
