# Generated by Django 6.0.4 on 2026-05-06 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_member_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberledger',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='members.member'),
        ),
        migrations.AlterField(
            model_name='membertopup',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='topups', to='members.member'),
        ),
    ]
