# Generated by Django 6.0.4 on 2026-05-08 00:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_alter_memberledger_member_alter_membertopup_member'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberledger',
            name='txn_type',
            field=models.CharField(choices=[('topup', 'Topup'), ('purchase', 'Purchase'), ('adjustment', 'Adjustment'), ('refund', 'Refund'), ('reversal_topup', 'Reversal Topup'), ('withdrawal', 'Withdrawal'), ('reversal_withdrawal', 'Reversal Withdrawal')], max_length=20),
        ),
        migrations.CreateModel(
            name='MemberWithdrawal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('withdrawal_number', models.CharField(blank=True, db_index=True, default='', max_length=40, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('approved', 'Approved'), ('reversed', 'Reversed')], default='approved', max_length=20)),
                ('reversed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='member_withdrawals', to=settings.AUTH_USER_MODEL)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='withdrawals', to='members.member')),
                ('reversal_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reversal_entries', to='members.memberwithdrawal')),
                ('reversed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='member_withdrawals_reversed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='memberledger',
            name='withdrawal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries', to='members.memberwithdrawal'),
        ),
    ]
