# Generated by Django 6.0.4 on 2026-06-04 06:23

import django.db.models.deletion
from django.db import migrations, models
from django.db.models import Count


def ensure_no_duplicate_money_ledgers(apps, schema_editor):
    MemberLedger = apps.get_model('members', 'MemberLedger')
    duplicate_topups = (
        MemberLedger.objects
        .exclude(topup_id__isnull=True)
        .values('topup_id')
        .annotate(total=Count('id'))
        .filter(total__gt=1)
    )
    if duplicate_topups.exists():
        sample = duplicate_topups.first()
        raise RuntimeError(
            f'MemberLedger memiliki ledger ganda untuk topup_id={sample["topup_id"]}. '
            'Bersihkan data duplikat sebelum menjalankan migration ini.'
        )

    duplicate_withdrawals = (
        MemberLedger.objects
        .exclude(withdrawal_id__isnull=True)
        .values('withdrawal_id')
        .annotate(total=Count('id'))
        .filter(total__gt=1)
    )
    if duplicate_withdrawals.exists():
        sample = duplicate_withdrawals.first()
        raise RuntimeError(
            f'MemberLedger memiliki ledger ganda untuk withdrawal_id={sample["withdrawal_id"]}. '
            'Bersihkan data duplikat sebelum menjalankan migration ini.'
        )


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_alter_memberledger_txn_type_memberwithdrawal_and_more'),
    ]

    operations = [
        migrations.RunPython(ensure_no_duplicate_money_ledgers, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='memberledger',
            name='topup',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entry', to='members.membertopup'),
        ),
        migrations.AlterField(
            model_name='memberledger',
            name='withdrawal',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entry', to='members.memberwithdrawal'),
        ),
    ]
