# Generated by Django 6.0.4 on 2026-06-04 06:33

from django.db import migrations, models
from django.db.models import Count


def _historical_ledger_key(ledger):
    if ledger.txn_type == 'topup' and ledger.topup_id:
        return f'TOPUP:{ledger.topup_id}'
    if ledger.txn_type == 'reversal_topup' and ledger.topup_id:
        topup = ledger.topup
        original_id = topup.reversal_of_id if topup and topup.reversal_of_id else ledger.topup_id
        return f'REV-TOPUP:{original_id}'
    if ledger.txn_type == 'purchase' and ledger.reference_code:
        return f'POS:{ledger.reference_code}'
    if ledger.txn_type == 'withdrawal' and ledger.withdrawal_id:
        return f'WITHDRAWAL:{ledger.withdrawal_id}'
    if ledger.txn_type == 'reversal_withdrawal' and ledger.withdrawal_id:
        withdrawal = ledger.withdrawal
        original_id = withdrawal.reversal_of_id if withdrawal and withdrawal.reversal_of_id else ledger.withdrawal_id
        return f'REV-WITHDRAWAL:{original_id}'
    return None


def populate_ledger_keys(apps, schema_editor):
    MemberLedger = apps.get_model('members', 'MemberLedger')
    ledgers = MemberLedger.objects.select_related('topup', 'withdrawal').order_by('id')
    for ledger in ledgers:
        key = _historical_ledger_key(ledger)
        if key:
            ledger.ledger_key = key
            ledger.save(update_fields=['ledger_key'])

    duplicates = (
        MemberLedger.objects
        .exclude(ledger_key__isnull=True)
        .values('ledger_key')
        .annotate(total=Count('id'))
        .filter(total__gt=1)
    )
    if duplicates.exists():
        sample = duplicates.first()
        raise RuntimeError(
            f'MemberLedger memiliki ledger_key duplikat: {sample["ledger_key"]}. '
            'Bersihkan data duplikat sebelum menjalankan migration ini.'
        )


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_alter_memberledger_topup_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberledger',
            name='ledger_key',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.RunPython(populate_ledger_keys, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='memberledger',
            name='ledger_key',
            field=models.CharField(blank=True, max_length=120, null=True, unique=True),
        ),
    ]
