# Generated by Django 6.0.4 on 2026-06-04 07:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0008_memberledger_ledger_key'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberDepositAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(choices=[('topup_request', 'Topup Request'), ('topup_approve', 'Topup Approve'), ('topup_reject', 'Topup Reject'), ('admin_topup', 'Admin Topup'), ('bulk_topup', 'Bulk Topup'), ('topup_reversal', 'Topup Reversal'), ('pos_debit', 'POS Debit'), ('withdrawal', 'Withdrawal'), ('withdrawal_reversal', 'Withdrawal Reversal')], db_index=True, max_length=40)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('balance_before', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('balance_after', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, default='', max_length=255)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='member_deposit_audit_logs', to=settings.AUTH_USER_MODEL)),
                ('ledger', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='members.memberledger')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deposit_audit_logs', to='members.member')),
                ('topup', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='members.membertopup')),
                ('withdrawal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='members.memberwithdrawal')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
