# Generated by Django 6.0.4 on 2026-05-03 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='client_txn_id',
            field=models.CharField(blank=True, db_index=True, max_length=80, null=True, unique=True),
        ),
    ]
