# Generated by Django 6.0.4 on 2026-05-03 06:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_sale_client_txn_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceiptPrintJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job_id', models.CharField(db_index=True, max_length=60, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('copies', models.PositiveIntegerField(default=1)),
                ('bridge_url', models.CharField(default='http://127.0.0.1:17971/print', max_length=255)),
                ('payload_json', models.TextField(default='')),
                ('response_json', models.TextField(default='')),
                ('last_error', models.CharField(blank=True, default='', max_length=255)),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='print_jobs', to='sales.sale')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
