# Generated by Django 6.0.4 on 2026-05-04 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_receiptprintjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='salepayment',
            name='change_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='salepayment',
            name='received_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
    ]
