# Generated by Django 6.0.4 on 2026-05-06 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_alter_memberledger_member_alter_membertopup_member'),
        ('sales', '0004_salepayment_change_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='members.member'),
        ),
    ]
