# Generated by Django 6.0.4 on 2026-09-24 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_alter_sale_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleitem',
            name='qty',
            field=models.DecimalField(decimal_places=3, max_digits=12),
        ),
    ]
